[package]
name = "arbintrary"
version = "0.1.0"
authors = ["npars <npars@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]
default = ["std"]
std = []